name: Node.js CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Use Node.js 21.x
              uses: actions/setup-node@v4
              with:
                  node-version: 21.x
            - name: Enable Corepack
              run: corepack enable
            - run: pnpm install --frozen-lockfile
            - run: pnpm run build
            - run: pnpm test
            - name: Upload results to Codecov
              uses: codecov/codecov-action@v4
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
