name: E2E

on:
    pull_request:
        branches: [main]
        types: [closed]

jobs:
    build:
        if: github.event.pull_request.merged == true
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@main
              with:
                  fetch-depth: 0
            - name: Use Node.js 23.x
              uses: actions/setup-node@v4
              with:
                  node-version: 23.x

            - name: Set up Bun
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest

            - name: Install dependencies
              run: bun install --frozen-lockfile

            - name: E2E
              run: bun run e2e:ci
              env:
                  SHAMELA_API_KEY: ${{secrets.SHAMELA_API_KEY}}
                  SHAMELA_API_MASTER_PATCH_ENDPOINT: ${{secrets.SHAMELA_API_MASTER_PATCH_ENDPOINT}}
                  SHAMELA_API_BOOKS_ENDPOINT: ${{secrets.SHAMELA_API_BOOKS_ENDPOINT}}
